version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    ignore:
      # docker/buildx + docker/cli + docker/docker require coordination to
      # ensure compatibility between them
      - dependency-name: "github.com/docker/buildx"
        # buildx is still 0.x
        update-types: ["version-update:semver-minor"]
      - dependency-name: "github.com/docker/cli"
        # docker/cli uses CalVer rather than SemVer
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "github.com/docker/docker"
        # docker/docker uses CalVer rather than SemVer
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
